name: Build and push docker images

on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/*'
      - '.github/*'
      - 'src/Dockerfile*'
      - 'src/rootfs/*'
      - 'src/hook/*'
      - 'src/VERSIONS'
      - 'src/*.sh'
      - 'src/VERSIONS'
      - 'tests/**'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/*'
      - '.github/*'
      - 'src/Dockerfile'
      - 'src/rootfs/*'
      - 'src/hook/*'
      - 'src/*.sh'
      - 'src/VERSIONS'
      - 'tests/**'

jobs:
  build:
    name: Build and push image to dockerhub
    runs-on: ubuntu-22.04
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: |
          echo  ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push images
        run: |
          cd ${GITHUB_WORKSPACE}/src/hook
          ./build.sh
          ./push.sh
